"""
Django settings for wabot project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dbplkcj7l9huvdpvsmk^un(vcu8r)_l5=k=td5fk*vy0xprtmo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'webhook.apps.WebhookConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wabot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wabot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'de5ku51srae4qm',
        'USER': 'ggcsbnfpfgfvki',
        'PASSWORD': '681a7ace9f99e828c9f9ba7d4ec87bbb8a9808e2567a89cf2b622f166c6b58d8',
        'HOST': 'ec2-52-205-61-230.compute-1.amazonaws.com',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

WA_VERIFY_TOKEN = "23rf313uf-9du2bbc0-cj382nsd-nc238"
WA_ENDPOINT = 'https://graph.facebook.com/v13.0/106519662119427/messages'

WA_HEADER = {
    "Authorization": "Bearer EABMCARdnUF8BAAyVqfQJ9JhptLYhAl4zt8pU6MhRMANK7MVObJvEUQIHwA1PN5zRigCpKG56Ki0xgSkCcOnZB9PQVU5jyWDDnAQzW5GuQj09VukPZAlQ2PZCsMmNb9RmZAd88HJkmaY9bUHO1jSp6TUDljljPeEO7iBEdkDfEyeun0x0FHFtlZBufB0Xk1pp0kVyJd0MdvrN47WR9usxN",
    "Content-Type": "application/json"
}

INTERACTIVE_MSG_BODY = {
    "type": "button",
    "body": {
        "text": "10. How did you come to know about 7Span?"
    },
    "footer": {
        "text": "Seven Bot"
    },
    "action": {
        "buttons": [
            {
              "type": "reply",
              "reply": {
                "id": "1",
                "title": "Referred by Friend"
              }
            },
            {
              "type": "reply",
              "reply": {
                "id": "2",
                "title": "Instagram/Facebook"
              }
            },
            {
              "type": "reply",
              "reply": {
                "id": "3",
                "title": "Other"
              }
            },
          ]
    }
}