# Generated by Django 4.0.6 on 2022-07-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0002_webhookmessage_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookmessage',
            name='message_id',
            field=models.CharField(max_length=100),
        ),
    ]
